# {
#     "newsletter_title" : "BigStep Team Official",
#     "images" : ["https://lh3.googleusercontent.com/chat_attachment/AFzxxOhNNoec15YlBfNHZ33l1lr6jb4Sh3ytb93YVUTN7MXVlKcJLsqFxoBCb5R3u6oGB0SuIIdvOtoYqyqFpMZdRviQPrkCgQPOuRZm1TGPjbXulH32ASEN74scAXoMI5G-PhXc-6kYGPn7K3aU1Yn5uBB8Z4-9ND5L-9iel26Gvcf6gfWNBjgn4G4ZUZMLumBVLXD8WmwZHPGTLy7X-Jrc7n657ORwTy0ikmkJ0d6ymAbjDw79Ncpq7WdzylO_ap8ZhpeXLT5wiFx05ojWQ8Yi30N6NRdePW0C3oYUt_POMDLenPbuhvuKhA2Sj9mkcw=w512",
#                 "https://lh3.googleusercontent.com/chat_attachment/AFzxxOgSOdWUeSTz4nTdtuGdnj1Z_DJAkEgky4JAu6YlB5eg7sxl6nsLSNQqF1kJ-UGDJ0hvawQwlprr4jNkVW9UGbtxJqRf6meLfvAwAiVyPfrHr0dncJ0zZywYbRcTMSUMqJaydYzYHuiJc71ycWGCw73mLHg9ISwetc3royQM58gwvKBzaoiDc4m_kR_VuveN7136QhwUCGWLhlZ55qTHoxnHID3Ct85wsJYhPzmRnJEl_n6W3jqGodFYGKva_Z9LJLpQnEdnwdjsxlFwOZmxGIdN_xv9Ox8wzD0u0NQPZsrGiVzTHNqPLKoZND-FAg=w512",
#                 "https://lh3.googleusercontent.com/chat_attachment/AFzxxOg3n79KsCrE4GRBvyESq48ZV45CT09qMPEj42VATIcdgj1FOPPbxPyktn08KzXGYLcpz-LGa3EyXJ9MHZHpwVKN4MHANcxjbuePCk9LL2kAu69y3rU_PPrG2QzenqjzG5JT1nGWf8nBWa4bwup4dhv9-WPUW6VFv4255Pmb-teHXQH5NmeIRzTV8M_oXmar0nFlKyTBoYcU0MtV-kTE7kQNykLTCjj2UZzGMaTFEl-a66L_HZLUoYcVkSAogDxEpkRwrTWqZmbH-q3MpdBNZDVwtzQi9w1-30-d8zjPV0mdeAbGlpNrIz4610tqlA=w512",
#                 "https://lh3.googleusercontent.com/chat_attachment/AFzxxOjZdDxxm6x81-Wv7gVrjnUwKbkviPd-qAXfAYSCIWs7t9JJzodFrWlUx1rhUycV42OqfR3njoIFA3LkNYyyePBvUzi8c5TlfMgMMVY9egSjFZKzP_hSJBe-OACbyLeuu7yBZ4EdS6s_AgnCaqXNBtl7nZ7AyWryOU5q_fUruN3VPU47RExogw3KqC4oXv2ZGE1DKL4UgXQ03pZ8r_ECCwRrHTbuh6NI1XyT2S5-SdyEfFsHIYg_5_lHl9tg8HQBCcwTCVQyBEo5mOrNBnVcGDMfWvGF-QRFyxlqsj45mBwAYF7Z1QZpQHsSqn6RkA=w512",
#                 "https://lh3.googleusercontent.com/chat_attachment/AFzxxOjzE0LXyEoV3b0fzBpGQ3Be7tsMdE385cBC6zSh9rbNwE3bH1dP8T8r9vagZhQSpA8jVhpKQ3mQTgjeT8jZOhRFzhOphfIpQUT0-NZvg_y0BDNFjOaJoA0HCXcPmc8yV0H3WGTy1UdzUAg8QQ3Lh2JdQlrB2mrqjjoeF6zxMo569H4qAMkqbXKbCsNzNXa0cBjcJkrDv17oaqwMeJK7XO33FJXlVJJh6-3hiVbj_1Hny1AtpftHKOql_BcshNiuE5J_2ubY44crD3fSL70SBILoqziPL5ndBxuOx8KWeW1FQ6yxvX7TAyt5tEtLng=w512"],
#     "messages":["Channelize.io has released a brand-new dashboard. The dashboard is the result of weeks of relentless dedication and hard work by the Channelize Team. We have already begun receiving positive feedback from our clients. This heartwarming response is a testament to the exceptional quality and value delivered by all of you.",
#                 "Bigstep is thrilled to announce yet another 5-star clutch review, recognizing our exceptional work in website restoration. This achievement reinforces our position as a leader in the industry and serves as a testament to our team's unmatched expertise and relentless pursuit of excellence. We are grateful for their dedication, passion, and innovative approach that consistently deliver remarkable outcomes.",
#                 "Riya Sharma and Himanshu Singh tweet their thanks to Sanjeev Kumar for his work. @RiyaSharma and @HimanshuSingh thank you for your great work. Keep doing great! @SanjeevKumar tweets back.",
#                 "Business Analysis and Requirements Gathering Phase is the cornerstone of achieving success in project execution. Do like, share, and comment!!https://www.linkedin.com/feed/update/urn:li:activity:7105904753439625217.",
#                 "Shivani Gaddi, Program Manager on Bespoke Augmented Reality and Video Editing Solutions with Banuba. We really appreciate Shivani's contribution to BigStep and the information that she has shared is really valuable for our readers. Give it a read and share your thoughts in the comments!!",
#                 "Bigstep is thrilled to announce yet another 5-star clutch review, recognizing our exceptional work in website restoration. This achievement reinforces our position as a leader in the industry and serves as a testament to our team's unmatched expertise and relentless pursuit of excellence."]          
# }

import os
os.environ["SACREBLEU"] = "1.5.1"
